### ISSUE TITLE
0.2.0.0 on hackage?

### ISSUE THREAD

**Issue by adarqui** [agrafix/ghcjs-ajax#1]
Hey agrafix!

Just wondering if it's possible to put 0.2.0.0 on hackage? I forked this repo and was about to add a "synchronous" sendRequest when I noticed it's been updated.

If not that's cool too. I can always just use stack.yaml I think.

Thanks!

**Comment by agrafix** [comment]
Sure, I could do that. Are you also aware that ghcjs-base already has ajax functionality built in? (see: https://github.com/ghcjs/ghcjs-base/blob/861ef792b91063cf01daa573bcb4d96f4db0cf09/JavaScript/Web/XMLHttpRequest.hs ). The api there is less concise, but more feature complete.

**Comment by adarqui** [comment]
@agrafix,

Sorry for the late response. Didn't notice it in my flood of emails. Thanks for the info! Yes I am aware. I used your "wrapper" because it is more attractive to someone beginning to use ghcjs. I've used it here for example:

https://github.com/adarqui/haskell-api-helpers-ghcjs/blob/master/src/Haskell/Api/Helpers.hs#L61

Thanks!

peace

**Comment by agrafix** [comment]
Okay, in that case I will put 0.2.0.0 on hackage today.

**Comment by adarqui** [comment]
Cool thanks alot!

Also, completely unrelated.. there's a small typo (programmig) on your personal site, at the bottom of the main page: (functional) programmig and more

**Comment by agrafix** [comment]
Voila: http://hackage.haskell.org/package/ghcjs-ajax-0.2.0.0

I've also fixed the typo, thanks for that ;-)

**Comment by adarqui** [comment]
@agrafix,

Thanks alot!
